version: "3.9"
services:
  worker:
    build: .
    volumes:
      - .:/code
      - logvolume01:/var/log
    links:
      - redis
    ports:
      - "3000:3000"  
    environment:
      PREFIX: ${PREFIX}
  redis:
    image: redis
volumes:
  logvolume01: {}
